// frontend/src/app/layout.tsx

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/context/AuthContext";
import Header from "@/components/header";
import { XAccountProvider } from "@/context/XAccountContext"; // <-- 追記

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={inter.className}>
        <AuthProvider>
          <XAccountProvider> {/* <-- 追記 */}
            <Header />
            <main>{children}</main>
          </XAccountProvider> {/* <-- 追記 */}
        </AuthProvider>
      </body>
    </html>
  );
}